# 模型相关
model:
  loader: llmtuner # 使用 llmtuner 加载器
  model_path: model/Qwen2.5-7B-Instruct-GPTQ-Int4 # 原始模型路径（必填）
  adapter_path: model/Muice-2.7.1-Qwen2.5-7B-Instruct-GPTQ-Int4-8e-4# # 微调模型路径（可选）
  template: qwen # LLaMA-Factory 中模型的模板（必填）
  system_prompt: '现在开始你是一个名为的“沐雪”的AI女孩子' # 系统提示（可选）
  auto_system_prompt: false # 自动配置沐雪的系统提示（默认为 false）
  max_tokens: 1024 # 模型生成的最大 token 数（可选，默认为 1024）
  temperature: 0.75 # 模型生成的温度参数（可选）
  top_k: 0.95 # 模型生成的 Top_k 参数（可选）

# Bot相关
bot:
  platform: qq # 聊天平台 qq/telegram
  id: 12345678 # 机器人QQ号
  port: 21050 # LLOneBot反向WebSocket服务端口
  wait_reply: true # 拟人化回复（回复前等待一段时间）
  cq_code: false # 是否解析CQ码
  anyone: false # 是否回复所有人
  trusted: # 可信QQ号(当anyone为false时生效)
    - 12345678 
  group:
    enable: true # 是否启用群聊回复
    only_at: true # 是否只回复at自己的消息
    rate: 0.5 # 群聊回复概率(only_at为false时生效)
    anyone: false # 是否回复所有群组
    trusted: # 可信群组(当anyone为false时生效)
      - 12345678
    only_trusted: false # 是否只回复可信QQ号
    cmd_only_trusted: false # 是否只执行可信QQ号的命令
  nonreply_prefix:  # 不回复消息的前缀
    - '!'
    - '！'
    - '#'
  nickname: '观众大大' # 用户昵称（当输出中包含 <USERNAME> 时生效）

# 主动对话相关
active:
  enable: false # 是否启用主动对话
  rate: 0.003 # 主动对话概率（每分钟）
  active_prompts:
    - '<生成推文: 胡思乱想>'
    - '<生成推文: AI生活>'
    - '<生成推文: AI思考>'
    - '<生成推文: 表达爱意>'
    - '<生成推文: 情感建议>'
  not_disturb: true # 是否开启免打扰模式
  shecdule:
    enable: true # 是否启用定时任务
    rate: 0.75 # 定时任务概率（每次）
    tasks:
      - hour: 8
        prompt: '<日常问候: 早上>'
      - hour: 12
        prompt: '<日常问候: 中午>'
      - hour: 18
        prompt: '<日常问候: 傍晚>'
      - hour: 22
        prompt: '<日常问候: 深夜>'
  targets: # 主动对话目标QQ号
    - 12345678
    - 23456789

# 其他可选服务
# OFA 图像识别
ofa_image:
  enable: false # 是否启用OFA图像服务
  path: ./model/ofa_image # OFA模型路径

# 语音回复
voice_reply:
  enable: false # 是否启用语音回复
  rate: 0.75 # 语音回复概率

# 实时语音对话(realtime_refence.py)
realtime_voice:
  path: ./model/SenseVoice # 实时语音模型路径

# Faiss长期记忆(Beta)
faiss:
  enable: true # 是否启用Faiss长期记忆
  path: ./model/distiluse-base-multilingual-cased-v1 # Faiss模型路径